# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.bar_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_progress.setProperty("value", 0)
        self.bar_progress.setTextVisible(False)
        self.bar_progress.setObjectName("bar_progress")
        self.gridLayout.addWidget(self.bar_progress, 2, 0, 1, 1)
        self.tab_transfers = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.tab_transfers.setFont(font)
        self.tab_transfers.setObjectName("tab_transfers")
        self.tab_transfer_queue = QtWidgets.QWidget()
        self.tab_transfer_queue.setObjectName("tab_transfer_queue")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_transfer_queue)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.list_transfer = QtWidgets.QListWidget(self.tab_transfer_queue)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(8)
        self.list_transfer.setFont(font)
        self.list_transfer.setObjectName("list_transfer")
        self.gridLayout_3.addWidget(self.list_transfer, 0, 0, 1, 1)
        self.tab_transfers.addTab(self.tab_transfer_queue, "")
        self.tab_transfer_complete = QtWidgets.QWidget()
        self.tab_transfer_complete.setObjectName("tab_transfer_complete")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_transfer_complete)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.list_finished_transfer = QtWidgets.QListWidget(self.tab_transfer_complete)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(8)
        self.list_finished_transfer.setFont(font)
        self.list_finished_transfer.setObjectName("list_finished_transfer")
        self.gridLayout_4.addWidget(self.list_finished_transfer, 0, 0, 1, 1)
        self.tab_transfers.addTab(self.tab_transfer_complete, "")
        self.gridLayout.addWidget(self.tab_transfers, 1, 0, 1, 1)
        self.tab_box = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.tab_box.setFont(font)
        self.tab_box.setObjectName("tab_box")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_log)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.list_log = QtWidgets.QListWidget(self.tab_log)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(8)
        self.list_log.setFont(font)
        self.list_log.setObjectName("list_log")
        self.gridLayout_5.addWidget(self.list_log, 0, 0, 1, 1)
        self.tab_box.addTab(self.tab_log, "")
        self.tab_credentials = QtWidgets.QWidget()
        self.tab_credentials.setObjectName("tab_credentials")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_credentials)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_hostname = QtWidgets.QLabel(self.tab_credentials)
        self.lbl_hostname.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_hostname.setObjectName("lbl_hostname")
        self.gridLayout_2.addWidget(self.lbl_hostname, 0, 0, 1, 1)
        self.input_hostname = QtWidgets.QLineEdit(self.tab_credentials)
        self.input_hostname.setObjectName("input_hostname")
        self.gridLayout_2.addWidget(self.input_hostname, 0, 1, 1, 3)
        self.lbl_username = QtWidgets.QLabel(self.tab_credentials)
        self.lbl_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_username.setObjectName("lbl_username")
        self.gridLayout_2.addWidget(self.lbl_username, 1, 0, 1, 1)
        self.input_username = QtWidgets.QLineEdit(self.tab_credentials)
        self.input_username.setObjectName("input_username")
        self.gridLayout_2.addWidget(self.input_username, 1, 1, 1, 3)
        self.lbl_password = QtWidgets.QLabel(self.tab_credentials)
        self.lbl_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_password.setObjectName("lbl_password")
        self.gridLayout_2.addWidget(self.lbl_password, 2, 0, 1, 1)
        self.input_password = QtWidgets.QLineEdit(self.tab_credentials)
        self.input_password.setObjectName("input_password")
        self.gridLayout_2.addWidget(self.input_password, 2, 1, 1, 3)
        self.btn_save_credentials = QtWidgets.QPushButton(self.tab_credentials)
        self.btn_save_credentials.setObjectName("btn_save_credentials")
        self.gridLayout_2.addWidget(self.btn_save_credentials, 3, 2, 1, 1)
        self.btn_test_credentials = QtWidgets.QPushButton(self.tab_credentials)
        self.btn_test_credentials.setObjectName("btn_test_credentials")
        self.gridLayout_2.addWidget(self.btn_test_credentials, 3, 3, 1, 1)
        self.btn_load_credentials = QtWidgets.QPushButton(self.tab_credentials)
        self.btn_load_credentials.setObjectName("btn_load_credentials")
        self.gridLayout_2.addWidget(self.btn_load_credentials, 3, 1, 1, 1)
        self.tab_box.addTab(self.tab_credentials, "")
        self.tab_sync = QtWidgets.QWidget()
        self.tab_sync.setObjectName("tab_sync")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_sync)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btn_add_sync = QtWidgets.QPushButton(self.tab_sync)
        self.btn_add_sync.setObjectName("btn_add_sync")
        self.gridLayout_6.addWidget(self.btn_add_sync, 3, 4, 1, 1)
        self.btn_load_sync = QtWidgets.QPushButton(self.tab_sync)
        self.btn_load_sync.setObjectName("btn_load_sync")
        self.gridLayout_6.addWidget(self.btn_load_sync, 3, 0, 1, 1)
        self.btn_sync = QtWidgets.QPushButton(self.tab_sync)
        self.btn_sync.setObjectName("btn_sync")
        self.gridLayout_6.addWidget(self.btn_sync, 3, 2, 1, 1)
        self.btn_rmv_sync = QtWidgets.QPushButton(self.tab_sync)
        self.btn_rmv_sync.setObjectName("btn_rmv_sync")
        self.gridLayout_6.addWidget(self.btn_rmv_sync, 3, 5, 1, 1)
        self.btn_save_sync = QtWidgets.QPushButton(self.tab_sync)
        self.btn_save_sync.setObjectName("btn_save_sync")
        self.gridLayout_6.addWidget(self.btn_save_sync, 3, 1, 1, 1)
        self.btn_clear_sync = QtWidgets.QPushButton(self.tab_sync)
        self.btn_clear_sync.setObjectName("btn_clear_sync")
        self.gridLayout_6.addWidget(self.btn_clear_sync, 3, 3, 1, 1)
        self.list_sync_files = QtWidgets.QListWidget(self.tab_sync)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(8)
        self.list_sync_files.setFont(font)
        self.list_sync_files.setObjectName("list_sync_files")
        self.gridLayout_6.addWidget(self.list_sync_files, 0, 0, 3, 3)
        self.list_sync_folders = QtWidgets.QListWidget(self.tab_sync)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(8)
        self.list_sync_folders.setFont(font)
        self.list_sync_folders.setObjectName("list_sync_folders")
        self.gridLayout_6.addWidget(self.list_sync_folders, 0, 3, 3, 3)
        self.tab_box.addTab(self.tab_sync, "")
        self.tab_browser = QtWidgets.QWidget()
        self.tab_browser.setObjectName("tab_browser")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_browser)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tree_browser = QtWidgets.QTreeWidget(self.tab_browser)
        self.tree_browser.setObjectName("tree_browser")
        self.tree_browser.headerItem().setText(0, "1")
        self.gridLayout_7.addWidget(self.tree_browser, 0, 0, 4, 1)
        self.btn_download_browser = QtWidgets.QPushButton(self.tab_browser)
        self.btn_download_browser.setObjectName("btn_download_browser")
        self.gridLayout_7.addWidget(self.btn_download_browser, 0, 1, 1, 1)
        self.btn_upload_browser = QtWidgets.QPushButton(self.tab_browser)
        self.btn_upload_browser.setObjectName("btn_upload_browser")
        self.gridLayout_7.addWidget(self.btn_upload_browser, 1, 1, 1, 1)
        self.btn_delete_browser = QtWidgets.QPushButton(self.tab_browser)
        self.btn_delete_browser.setObjectName("btn_delete_browser")
        self.gridLayout_7.addWidget(self.btn_delete_browser, 2, 1, 1, 1)
        self.btn_refresh_browser = QtWidgets.QPushButton(self.tab_browser)
        self.btn_refresh_browser.setObjectName("btn_refresh_browser")
        self.gridLayout_7.addWidget(self.btn_refresh_browser, 3, 1, 1, 1)
        self.tab_box.addTab(self.tab_browser, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.tab_box.addTab(self.tab_settings, "")
        self.gridLayout.addWidget(self.tab_box, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_transfers.setCurrentIndex(1)
        self.tab_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_transfers.setTabText(self.tab_transfers.indexOf(self.tab_transfer_queue), _translate("MainWindow", "Transfer Queue"))
        self.tab_transfers.setTabText(self.tab_transfers.indexOf(self.tab_transfer_complete), _translate("MainWindow", "Complete Transfers"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_log), _translate("MainWindow", "Log"))
        self.lbl_hostname.setText(_translate("MainWindow", "<html><head/><body><p>Hostname:</p></body></html>"))
        self.lbl_username.setText(_translate("MainWindow", "Username:"))
        self.lbl_password.setText(_translate("MainWindow", "Password:"))
        self.btn_save_credentials.setText(_translate("MainWindow", "Save"))
        self.btn_test_credentials.setText(_translate("MainWindow", "Test"))
        self.btn_load_credentials.setText(_translate("MainWindow", "Load"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_credentials), _translate("MainWindow", "Credentials"))
        self.btn_add_sync.setText(_translate("MainWindow", "Add"))
        self.btn_load_sync.setText(_translate("MainWindow", "Load"))
        self.btn_sync.setText(_translate("MainWindow", "Sync"))
        self.btn_rmv_sync.setText(_translate("MainWindow", "Remove"))
        self.btn_save_sync.setText(_translate("MainWindow", "Save"))
        self.btn_clear_sync.setText(_translate("MainWindow", "Clear"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_sync), _translate("MainWindow", "Sync"))
        self.btn_download_browser.setText(_translate("MainWindow", "Download"))
        self.btn_upload_browser.setText(_translate("MainWindow", "Upload"))
        self.btn_delete_browser.setText(_translate("MainWindow", "Delete"))
        self.btn_refresh_browser.setText(_translate("MainWindow", "Refresh"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_browser), _translate("MainWindow", "File Browser"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_settings), _translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

